### ISSUE TITLE
Paho error on reconnect

### ISSUE THREAD

**Issue by igenius-code** [iGenius-Srl/android-mqtt-service#2]
```java
MQTT error. RequestId: .mqtt.connect-and-subscribe/ce01d296-2595-4b6c-9a8f-967a0cfec653
MqttException (0) - java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
    at net.igenius.mqttservice.MQTTService.onConnect(MQTTService.java:172)
    at net.igenius.mqttservice.MQTTService.run(MQTTService.java:112)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Timer.cancel()' on a null object reference
    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.stopReconnectCycle(MqttAsyncClient.java:1120)
    at org.eclipse.paho.client.mqttv3.MqttAsyncClient.reconnect(MqttAsyncClient.java:1057)
    at org.eclipse.paho.client.mqttv3.MqttClient.reconnect(MqttClient.java:524)
    at net.igenius.mqttservice.MQTTService.reconnect(MQTTService.java:186)
    at net.igenius.mqttservice.MQTTService.onConnect(MQTTService.java:166)
    at net.igenius.mqttservice.MQTTService.run(MQTTService.java:112) 
    at android.os.Handler.handleCallback(Handler.java:751) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.os.HandlerThread.run(HandlerThread.java:61) 
```

**Comment by gotev** [comment]
Moved to https://github.com/iGenius-Srl/paho.mqtt.java/issues/2

**Comment by jabedhasan21** [comment]
Is there any update regarding this issue.I am facing the same issue
